### ISSUE TITLE
`viur deploy` should provide a helpful hint

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-cli#131]
For version 2:
```
$ viur deploy app 
Usage: viur [OPTIONS] COMMAND [ARGS]...
Try 'viur -h' for help.

Error: No such command 'deploy'.
$ viur cloud deploy app
✔ No vulnerabilities found.
Do you want to regenerate the requirements.txt located in the ./deploy? [y/N]: y
requirements.txt successfully generated
```

Can `viur deploy app` please still provide a helpful error message, like: `Sorry, 'viur deploy'  is now known as 'viur cloud deploy'`...

**Comment by Grashalmbeisser** [comment]
![image](https://github.com/viur-framework/viur-cli/assets/57599830/788e0475-842b-48a1-a660-9ef51031ffbe)

'viur deploy' aswell as 'viur install' return deprecation warnings!

This change was made with version 2.0.0
