### ISSUE TITLE
v.2.0.0 Core Version Check does weird things: project.json needs several core definitions, otherwise error is thrown

### ISSUE THREAD

**Issue by xnopasaranx** [viur-framework/viur-cli#138]
https://github.com/viur-framework/viur-cli/blob/8e39616362ed051b9bba0d51d71601b12479bdfd/src/viur_cli/conf.py#L116C1-L117C1

I am not sure if this is the correct place in the code, but in the readme it says, that the default object is now the one which should contain "core" version. If only that is defined, viur-cli will move it out of default and up one level and error out. If we define the core version again a second time inside default, it will be respected and viur-cli will continue. This happens when trying to init or deploy a project.

Why is a core version necessary here anyway? Core should be installed via PyPi package, it can be different depending on which deployment target, but we have the actual version for a branch defined in the Pipfile.

**Comment by Grashalmbeisser** [comment]
That seems to be an issue, however a workaround for this issue is, to manually write an entry of your needed core version in you project.json profile entry.

**Comment by phorward** [comment]
The viur-core version should not be saved into the `project.json`, as it is a redundant information.
