### ISSUE TITLE
viur create calls clean_base.py with application-name-parameter even if not set 

### ISSUE THREAD

**Issue by bb-mausbrand** [viur-framework/viur-cli#153]
Running viur create [project-name] runs clean_base.py with parameter -A [project-name] even if it istn't properly configured. This leads i.e. to the application name being "{{app_id}}"

**Comment by bb-mausbrand** [comment]
it should have changed two lines in deploy/main.py:
34: conf["viur.validApplicationIDs"] = ["{{app_id}}"]
88: conf["admin.name"] = "{{app_id}}"

**Comment by phorward** [comment]
Should be resolved together with #165.
