### ISSUE TITLE
Statement with no effect

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-cli#167]
I found this statement, it does nothing.

https://github.com/viur-framework/viur-cli/blob/25a73b05bc0e769a798422b8d8f907c388747c87/src/viur_cli/conf.py#L171

**Comment by sveneberth** [comment]
#175 has not touched this line of code in any way ?!

**Comment by Grashalmbeisser** [comment]
> #175 has not touched this line of code in any way ?!

Yeah, imissclicked. mb.
