### ISSUE TITLE
Integrate tools from viur-tools into viur-cli

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-cli#3]
The Repository [https://github.com/phorward/viur-tools](https://github.com/phorward/viur-tools) contains further tools which could be implemented into viur-cli as well.

- [ ] csvimport.py is a generic CSV-importing tool => What about `viur-cli import` command for that?
- [x] viur-2to3.py is a draft for porting projects from ViUR2 to ViUR3 => What about a `viur-cli 2to3` command?

The other tools like updatedb.sh, copyblobs.py or copydb.py are only relevant to ViUR2 and should be ignored.

**Comment by Grashalmbeisser** [comment]
Due to viur-scriptor added in the viur-ecosystem i would propose to not implement the .csv importe as an cli tool and rather write a generalized scriptor-script instead.

**Comment by Grashalmbeisser** [comment]
Its already handled.
