### ISSUE TITLE
Add more explainations to the questions.

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-cli#41]
After upgrading ViUR-cli to 1.0.3 and running it for the first time, I was very confused and had no idea how to answer these questions:

```
$ viur run develop
viur-cli tries to find npm applications
Do you want to add / to your apps? [y/N]: y
name []: sources
command [build]: 
Do you want to add /viur-scriptor/ to your apps? [y/N]: y
name [scriptor]: 
command [build]: 
Do you want to add /viur-scriptor/src/usepython/ to your apps? [y/N]: y
name [scriptor_usepython]: 
command [build]: 
```
 * What is the `/`?
 * What name does it expect?
 * Do I need usepython? Isn't it part of the scriptor?

**Comment by phorward** [comment]
IMHO, this entire process is irrelevant for daily use. Developers should edit `project.json` manually, and not be prompted with a semi-working assistant that generates broken build-entries. Please remove these questions entirely.
