### ISSUE TITLE
Please update app-server to v0.9.9

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-cli#97]
and please don't use these fixed versions. At least at patch level it should be relaxed.

I recommend to use [`~=`](https://peps.python.org/pep-0440/#compatible-release) like `app-server~=0.9.9`

**Comment by sveneberth** [comment]
@Grashalmbeisser  Can you please release this as v1.1.2?

**Comment by Grashalmbeisser** [comment]
is relesed to pypi https://pypi.org/project/viur-cli/
